version: '3.8'
   services:
     backend:
       build: ./backend
       ports:
         - "5000:5000"
       environment:
         - DB_HOST=postgres
         - DB_USER=postgres
         - DB_PASSWORD=yourpassword
         - DB_NAME=travel_db
         - DB_PORT=5432
         - REDIS_HOST=redis
         - REDIS_PORT=6379
         - PORT=5000
       depends_on:
         - postgres
         - redis
     frontend:
       build: ./frontend
       ports:
         - "3000:3000"
       depends_on:
         - backend
     postgres:
       image: postgres:latest
       environment:
         POSTGRES_USER: postgres
         POSTGRES_PASSWORD: yourpassword
         POSTGRES_DB: travel_db
       volumes:
         - postgres_data:/var/lib/postgresql/data
         - ./init.sql:/docker-entrypoint-initdb.d/init.sql
     redis:
       image: redis:latest
       ports:
         - "6379:6379"
   volumes:
     postgres_data: